# Generated by Django 5.1 on 2024-10-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=5000)),
                ("title", models.CharField(max_length=5000)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="")),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
